# @name CreateEvent
POST http://localhost:3333/events
Content-Type: application/json

{
    "name": "Event",
    "description": "One more description",
    "date": "2025-03-15T11:00:00",
    "price": 200
}

###

@eventId = {{ CreateEvent.response.body.id }} 

###

# @name GetEvents
GET http://localhost:3333/events

###

# @name GetEvent
GET http://localhost:3333/events/{{eventId}}

###

# @name UpdateEvent
PATCH http://localhost:3333/events/{{eventId}}
Content-Type: application/json

{
    "name": "Media Day",
    "description": "One more description",
    "date": "2025-03-15T11:00:00",
    "price": 300
}

###

# @name DeleteEvent
DELETE http://localhost:3333/events/{{eventId}}

###

# @name GetSpots
GET http://localhost:3333/events/{{eventId}}/spots

###

# @name CreateSpot
POST http://localhost:3333/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A3"
}

###

@spotId = {{ CreateSpot.response.body.id }}
@spotName = {{ CreateSpot.response.body.name }}

###

# @name GetSpot
GET http://localhost:3333/events/{{eventId}}/spots/{{spotId}}

###

# @name UpdateSpot
PATCH http://localhost:3333/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
    "name": "Spot 1"
}

###

# @name DeleteSpot
DELETE http://localhost:3333/events/{{eventId}}/spots/{{spotId}}

###

# @name Reserve
POST http://localhost:3333/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
    "spots": [
        "A3"
    ],
    "ticketKind": "FULL",
    "email": "alerrandro@email.com"
}