services:
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
